name: user_input_PR


on:
  push:
      branches:
          - 'user_changes*'
          
jobs:
  trigger_appsAway:
    runs-on: ubuntu-latest
    steps:
    
    - name: print event
      run: echo " ${{ toJson(github.event) }}"
      
    - name: Parse branch name
      id: parsed_branch
      run: |
        echo ::set-output name=branch::$(echo ${{ github.event.ref }} | sed -nr 's/.*refs\/heads\/(.*)/\1/p')
        
    - name: Get Token
      id: get_workflow_token
      uses: tibdex/github-app-token@v1
      with:
        private_key: ${{ secrets.ILARIA_APP_KEY }}
        app_id: ${{ secrets.ILARIA_APP_ID }}
        repository: my-organization-for-testing/human-sensing
        
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      env:
        GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      with:
        token: ${{ env.GITHUB_APPS_TOKEN }}
        repository: my-organization-for-testing/human-sensing
        event-type: user_changes
        client-payload: '{ "type": "user_changes", "token": "${{ env.GITHUB_APPS_TOKEN }}", "branch_name": "${{ steps.parsed_branch.outputs.branch }}" }'
